before_script:
  - apt update
  - DEBIAN_FRONTEND=noninteractive apt install -yq build-essential cmake git

build:debian:10:
  stage: build
  image: debian:10
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O1 -g' ..
    - make

build:ubuntu:20.04:
  stage: build
  image: ubuntu:20.04
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O1 -g' ..
    - make

build:ubuntu:20.10:
  stage: build
  image: ubuntu:20.10
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O1 -g' ..
    - make

